apiVersion: v1
kind: Service
metadata:
  name: payment-gateway-connector
  namespace: orbitpay
  labels:
    app.kubernetes.io/name: payment-gateway-connector
    app.kubernetes.io/part-of: orbitpay
    app.kubernetes.io/component: payment-processing
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: payment-gateway-connector
    app.kubernetes.io/part-of: orbitpay
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
