apiVersion: v1
kind: ServiceAccount
metadata:
  name: payment-gateway-connector
  namespace: orbitpay
  labels:
    app.kubernetes.io/name: payment-gateway-connector
    app.kubernetes.io/part-of: orbitpay
    app.kubernetes.io/component: payment-processing
automountServiceAccountToken: false
